Repository NervanaSystems/coach, pull requests merged in 2019-05, with the labels that each got.

#301 tests: fixed nightly
  .circleci/config.yml
  rl_coach/tests/test_checkpoint.py
  rl_coach/tests/test_coach_args.py
  rl_coach/tests/utils/args_utils.py
Labels: test

#304 tests: weekly deployment
  .circleci/config.yml
Labels: test

#315 tests: fix traces export presets
  .circleci/config.yml
Labels: test

#325 removed timestep_limit due to gym version upgrade
  rl_coach/environments/gym_environment.py
Labels: bug

#316 tests: fix traces and changing workflow jobs
  .circleci/config.yml
  rl_coach/tests/trace_tests.py
Labels: test

#292 Add head regularization costs to tf.losses
  rl_coach/architectures/tensorflow_components/heads/head.py
Labels: priority/p1

#327 tests: print logs on failure + fix -cp param
  rl_coach/tests/test_coach_args.py
  rl_coach/tests/utils/args_utils.py
Labels: test

#335 increase timeout for golden tests
  .circleci/config.yml
Labels: test

#336 Removed unnecessary futures dependency
  requirements.txt
Labels: bug
